### ISSUE TITLE
NameError: uninitialized constant GData

### ISSUE THREAD

**Issue by rgarro** [tokumine/GData#5]
Im including gem "gdata_19", :git=>'git://github.com/tokumine/GData.git'
in my ruby 1.9 rails3 project via Gem file.
After bundle install 

Loading development environment (Rails 3.1.3)
1.9.2-p290 :001 > yt = GData::Client::YouTube.new
NameError: uninitialized constant GData
    from (irb):1
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:45:in `start'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:8:in`start'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Is there something Im missing before using gdata_19?

**Comment by rgarro** [comment]
a require 'gdata' on my app controller fixed it
