### ISSUE TITLE
Gdata not uploading a photo on Ruby 2.0

### ISSUE THREAD

**Issue by yuraksisa** [tokumine/GData#9]
I can't upload a photo using gdata_19 and ruby 2.0

Here I include the trace. 

2013-09-15T09:24:21.834424+00:00 app[web.1]: ArgumentError - wrong number of arguments (2 for 1):
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gdata_19-1.1.5/lib/gdata/http/mime_body.rb:37:in `read'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/generic_request.rb:197:in`copy_stream'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/generic_request.rb:197:in `send_request_with_body_stream'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http/generic_request.rb:132:in`exec'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1404:in `block in transport_request'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1403:in`catch'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1376:in`request'
2013-09-15T09:24:21.834424+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/net.rb:30:in `block in request_with_newrelic_trace'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/cross_app_tracing.rb:43:in`trace_http_request'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/net.rb:29:in `request_with_newrelic_trace'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1369:in`block in request'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:852:in `start'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:1367:in`request'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/net.rb:33:in `request_with_newrelic_trace'
2013-09-15T09:24:21.834642+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gdata_19-1.1.5/lib/gdata/http/default_service.rb:71:in`make_request'

**Comment by rkamun1** [comment]
Hi,

Did you ever figure this out?
